enum SETUP_ENUM {
  CHARGE_CONFIG_PAYMENT = "CHARGE_CONFIG_PAYMENT",
  CONFIG_PAYOUT = "CONFIG_PAYOUT",
  CONFIG_PROMAX = "CONFIG_PROMAX",
  CONFIG_WEBHOOK_PAYMENT_IN = "CONFIG_WEBHOOK_PAYMENT_IN",
  IMPORT_CLIENTS = "IMPORT_CLIENTS",
  IMPORT_DRIVERS = "IMPORT_DRIVERS",
  IMPORT_CONDITION_PAYMENT = "IMPORT_CONDITION_PAYMENT",
}

export default SETUP_ENUM;
